[workspace.package]
authors = ["Sherry"]
edition = "2021"
repository = ""
license = "GPL-3.0-only"
homepage = "https://paritytech.github.io/polkadot-sdk/"


[workspace]
members = [ 
	"super-basic-pallet",
	"shell-pallet",
]